__author__ = 'raphey'

import numpy as np
import cv2
import matplotlib.pyplot as plt


# Tool to retrieve clicks, from
class ClickClass():
    def __init__(self, filepath):
        self.fname = filepath
        self.img = cv2.imread(self.fname)
        self.point = ()

    def getCoord(self):
        fig = plt.figure()
        fig.add_subplot(111)
        plt.imshow(self.img)
        fig.canvas.mpl_connect('button_press_event', self.__onclick__)
        plt.show()
        return self.point

    def __onclick__(self, click):
        self.point = (click.xdata, click.ydata)
        print(np.round(self.point))
        return self.point


def print_positive_examples():
    click = ClickClass('images/test_array_1_hi_res.png')
    click.getCoord()


def show_positive_coords(img, pos_coords):
    output = img.copy()
    for x, y in pos_coords:
        cv2.circle(output, (x, y), 3, (0, 0, 255), 1)

    cv2.imshow("output", output)
    cv2.waitKey(0)


def save_training_data_from_coords(img, pos_coords, pos_radius=1.0, neg_gap=0.0,
                                   neg_stride=2, edge_border=12):
    """
    Saves a series of 9x9 sections of img based on positive example coordinate pairs.
    Also grabs positive images located within pos_radius of given coordinate pairs.
    Negative examples are generated by moving with neg_stride across image, within
    edge_border from edge, grabbing images that are at least pos_radius + neg_gap from
    positive coordinates.
    """
    for x, y in pos_coords:
        cv2.imshow("output", grab_9x9_image_section(img, x, y))
        cv2.waitKey(0)


def grab_9x9_image_section(img, x, y):
    assert(4 <= x < len(image[0]) and 4 <= y < len(image))
    return img[y - 4: y + 5, x - 4: x + 5]


# Load image and convert image to grayscale
image_path = 'images/test_array_1_hi_res.png'
image = cv2.imread(image_path)
grayscale_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Load positive example coordinates from csv
pos_data = np.loadtxt(open("cell_coords.csv", "rb"), delimiter=",", skiprows=1, dtype=int)

save_training_data_from_coords(grayscale_image, pos_data)